# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

apiVersion: apps/v1
kind: Deployment
metadata:
    name: aspnetapp-deployment
    labels:
        app: aspnetapp-azure
spec:
    replicas: 1
    selector:
        matchLabels:
            app: aspnetapp-azure
    template:
        metadata:
            labels:
                app: aspnetapp-azure
        spec:
            nodeSelector:
                "aspnetapp-devops-d1e2ead6.hcp.eastus.azmk8s.io/os": linux
            containers:
            -   name: aspnetapp
                image: svspriyan.azurecr.io/aspnetapp
                ports:
                -   containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: aspnetapp-azure
spec:
    type: LoadBalancer
    ports:
    -   port: 80
    selector:
        app: aspnetapp-azure
        